### ISSUE TITLE
Nasa WMS is unavailable

### ISSUE THREAD

**Issue by annarieger** [terrestris/react-geo-client-template#46]
[Nasa WMS](https://neo.gsfc.nasa.gov/wms/wms/) seems to be more often unavailable. Due to this, the tests relaying on it, are [failing](https://github.com/terrestris/react-geo-client-template/runs/6252342723?check_suite_focus=true#step:7:99).

We should possibly switch to some another service to to increase the stability.

**Comment by dnlkoch** [comment]
Fixed via [#1061](https://github.com/terrestris/react-geo-client-template/pull/1061).
